package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u331/2416/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Thursday, March 10, 2022 3:16:12 AM PST
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
   * Constant, defined in the Messaging spec, to define how far the 
   * request shall progress before control is returned to the client.
   */
  public static final short value = (short)(1);
}
