package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u331/2416/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, March 10, 2022 3:16:12 AM PST
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
	 * The value representing ID_ASSIGNMENT_POLICY_ID.
	 */
  public static final int value = (int)(19L);
}
